---
apiVersion: v1
kind: Service
metadata:
  name: nginx-tacos-service
spec:
  selector:
    app: nginx-tacos
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-tacos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-tacos
  template:
    metadata:
      labels:
        app: nginx-tacos
    spec:
      containers:
      - name: tacos
        image: philippe1jonathan/restaurants:tacos
        ports:
        - containerPort: 80