---
apiVersion: v1
kind: Service
metadata:
  name: nginx-pizza-service
spec:
  selector:
    app: nginx-pizza
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pizza-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pizza
  template:
    metadata:
      labels:
        app: nginx-pizza
    spec:
      containers:
      - name: pizza
        image: philippe1jonathan/restaurants:pizza
        ports:
        - containerPort: 80